<?php
$projectRoot = __DIR__;
while ($projectRoot !== dirname($projectRoot) && !is_file($projectRoot . '/API/config.php')) {
    $projectRoot = dirname($projectRoot);
}
require_once $projectRoot . '/API/config.php';
$enlace = getDBConnection();



if (isset($_POST["DatosBiblioteca"])){
    //RECIBIR TODOS LOS DATOS DE LA TABLA

    $TITULOS = $_POST["TITULOS"];
    $TIPO_CLASIFICACION_LC =$_POST ["TIPO DE CLASIFICACION"];
    $TITULOS_CLASIFICADOS = $_POST ["TITULOS_CLASIFICADOS"];
    $VOLUMENES = $_POST["VOLUMENES_CLASIFICADOS"];
    $LIBROS_PRESTADOS_SALA = $_POST["LIBROS PRESTADOS EN SALA"];
    $LIBROS_PRESTADOS_DOMILICIO = $_POST ["LIBROS PRESTADOS A DOMICILIO"];
    $PUBLICACIONES_PERIODICAS = $_POST["PUBLICACIONES PERIODICAS"];
    $TOTAL_USUARIOS_PERIODO = $_POST["TOTAL DE USUARIOS EN EL PERIODO"];
    $CAPACIDAD_DE_USUARIOS_SALA = $_POST["CAPACIDAD DE USUARIOS EN SALA"];
    $PC_INTERNET= $_POST["PC´S CON INTERNERT"];
    $PC_SIN_INTERNET = $_POST["PC´S SIN INTERNET"];
    $CONSULTAS_ALUMNOS = $_POST["CONSULTAS DE ALUMNOS"];
    $CONSULTAS_DOCENTES = $_POST["CONSULTAS DE DOCENTES"];


}
